version: '3.3'
volumes:
  keycloak-db-data:
    driver: local

 

services:
  postgres:
    image: postgres:13.7
    container_name: postgres
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${KEYCLOAK_DATABASE_NAME}
      - POSTGRES_USER=${KEYCLOAK_DATABASE_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
  keycloak:
    build: .
    container_name: keycloak-test-theme
    ports:
      - 8443:8443
      - 8080:8080
    environment:
      - DB_DATABASE=${KEYCLOAK_DATABASE_NAME}
      - DB_USER=${KEYCLOAK_DATABASE_USER}
      - DB_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
      - DB_ADDR=${KEYCLOAK_DATABASE_HOST}
      - DB_VENDOR=${KEYCLOAK_DATABASE_VENDOR}
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - KC_HTTP_PORT=8080
      - KC_SPI_THEME_WELCOME_THEME=my-theme
      - KC_SPI_THEME_ACCOUNT_THEME=my-theme
      - KC_SPI_THEME_LOGIN_THEME=my-theme
    volumes:
      - ./themes/my-theme:/opt/keycloak/themes/my-theme/
    depends_on:
      - postgres
    command:
      - start-dev
      - --import-realm
      - --http-relative-path=/auth








